[parity]
# Custom chain
chain = "Playground.json"
base_path = "./node"
# Auto-updates to every release
auto_update = "all"
# Stable
release_track = "beta"

[network]
port = 30300

[account]
# Disables hardware wallet support.
disable_hardware = true
password = ["node.pwds"]

[rpc]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"
port = 8540
# Allows Cross-Origin Requests from domain 'playground.lamarkaz.com.
cors = ["*"]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "private", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "parity"]

[websockets]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"
port = 8450
# Allows connecting from Origin 'parity://*,chrome-extension://*,moz-extension://*,https://*,wss://*'.
origins = ["*"]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "parity_pubsub", "private", "traces", "rpc", "shh", "shh_pubsub", "parity"]

[secretstore]
# You won't be able to encrypt and decrypt secrets.
disable = true

[mining]
# Account to sign consensus messages and issue blocks for non-PoW chains.
engine_signer = "0xbf7914020229016b03983d0b25e8f5a36b54c059"
# Targeting 10000000 gas per block when sealing a new block.
gas_floor_target = "10000000"
# Gas limit will be raised at most by 10000000 gas.
gas_cap = "10000000"

[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Keep all state trie data. No pruning.
pruning = "archive"
# Enables Fat DB
fat_db = "on"
