# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Custom chain
chain = "Playground.json"
base_path = "/tmp/playground"
# Auto-updates to every release
auto_update = "all"
# Stable
release_track = "stable"

[network]
port = 30300

[account]
# Disables hardware wallet support.
disable_hardware = true
password = ["node.pwds"]

[rpc]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"
port = 8540
# Allows Cross-Origin Requests from domain 'playground.lamarkaz.com.
cors = ["playground.lamarkaz.com"]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "private", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]

[websockets]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"
port = 8450
# Allows connecting from Origin 'parity://*,chrome-extension://*,moz-extension://*,https://*,wss://*'.
origins = ["parity://*", "chrome-extension://*", "moz-extension://*", "https://*", "wss://*"]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "parity_pubsub", "private", "traces", "rpc", "shh", "shh_pubsub"]

[secretstore]
# You won't be able to encrypt and decrypt secrets.
disable = true

[mining]
# Account to sign consensus messages and issue blocks for non-PoW chains.
engine_signer = "0x64591b90a9c1d09e413562f5489d29b89ca05b27"
# You will be paid $0 for a basic transaction - Minimum gas price will be set accordingly.
usd_per_tx = "0"
# Targeting 10000000 gas per block when sealing a new block.
gas_floor_target = "10000000"
# Gas limit will be raised at most by 10000000 gas.
gas_cap = "10000000"
# Txs in the queue are ordered by gas (low gas = high priority)
tx_queue_strategy = "gas"

[footprint]
# Keep all state trie data. No pruning.
pruning = "archive"