[parity]
# Custom chain
chain = "Playground.json"
base_path = "./node"
# Auto-updates to every release
auto_update = "all"
# Beta
release_track = "beta"

[network]
port = 30300

[rpc]
port = 8540
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "private", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "parity"]

[websockets]
port = 8450
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "parity_pubsub", "private", "traces", "rpc", "shh", "shh_pubsub", "parity"]

[secretstore]
# You won't be able to encrypt and decrypt secrets.
disable = true